#!/bin/bash

cd ..
# cleanup old build
rm -r dist
# use virtual environment
source src/venv/bin/activate
# get pyinstaller
pip install pyinstaller
# create spec file
pyinstaller --clean -ywF -i src/icon.ico -n collisions src/main.py
# build exe
pyinstaller -y collisions.spec
# unix setup
mv dist/collisions dist/collisions_e
mkdir dist/collisions
mv dist/collisions_e dist/collisions/collisions
# copy in assets
cp -r src/assets dist/collisions/assets
# copy in license
cp LICENSE.txt dist/collisions/
# copy in readme
cp README.txt dist/collisions/
# linux cleanup
sed -i 's/collisions.exe/collisions/g' dist/collisions/README.txt
# unix final
chmod +x dist/collisions
# cleanup
deactivate
rm -r build
rm collisions.spec
